version: '3.1'

services:
  nats:
    image: nats
    restart: always
    ports:
      - "4222:4222"
  api:
    build: './api'
    restart: always
    ports:
      - "8080:8080"
    environment:
      TOPIC: "messageboard"
      NATS: "nats://nats:4222"
      NATSUSER: "ruser"
      NATSPASS: "T0pS3cr3t"
    depends_on:
      - nats
  notificationcenter:
    build: './notification-center'
    restart: always
    ports:
      - "8081:8080"
    environment:
      TOPIC: "messageboard"
      NATS: "nats://nats:4222"
      NATSUSER: "ruser"
      NATSPASS: "T0pS3cr3t"
    depends_on:
      - nats
  client:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./client:/usr/share/nginx/html:ro"
